name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Python Week 3
      id: python-week-3
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 60
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYTHON-WEEK-3_RESULTS: "${{steps.python-week-3.outputs.result}}"
      with:
        runners: python-week-3
